### ISSUE TITLE
Make Article text a bit larger

### ISSUE THREAD

**Issue by codykraatz** [vta/hub#8]

**Comment by jaeha1** [comment]
It's done.

**Comment by jaeha1** [comment]
I’ve updated the article page template based on today’s meeting discussion. Body text is bigger and main photo is placed on the right top corner. Let me know what you think and if you like it, I can apply to other two article pages for your presentation.

**Comment by jaeha1** [comment]
Here is a link to the article page that I updated: https://sccvta.sharepoint.com/sites/hubbeta/Pages/ERT.aspx
